// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://notvufknqzidbinccbim.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5vdHZ1ZmtucXppZGJpbmNjYmltIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxMzA3NzQsImV4cCI6MjA2MjcwNjc3NH0.IPNXcJFJpe4yri7uGrhm8tVYc3n73KLbyAyFkfTGMg0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);